import React, { Fragment } from "react"
export const themeColorold = "#14ADED"
export const themeColor = "#3e64a3"
export const themeColorButton = "#2aabe2"
export const themeColorSlogan = "#000"
export const themeColorInputBorder = "#72c1f3"
export const themeColorInputPlaceholder = "#b0b0b0"
export const themeColorVideosHeader = "#2aabe2"
export const themeColorWhite = "#fff"
export const themeColorRedSky = "#fc5288"

export const adsList = {
  Services: [
    { id: "se1", name: "Skilled Technician" },
    { id: "se2", name: "Real Estate" },
    { id: "se3", name: "Animal" },
    { id: "se4", name: "Aquatic" },
    { id: "se5", name: "Lessons and Educational Development" },
    { id: "se7", name: "General Labor and Moving" },
    { id: "se8", name: "Household/Farm/Garden" },
    { id: "se9", name: "Financial" },
    { id: "se10", name: "Ceremony and Event" },
    { id: "se11", name: "Electronic" },
    { id: "se12", name: "Beauty" },
    { id: "se13", name: "Automobile" },
  ],
  Housing: [
    { id: "ho1", name: "Vacation Rentals" },
    { id: "ho2", name: "Sublease" },
    { id: "ho3", name: "Rooms" },
    { id: "ho4", name: "Real Estate" },
    { id: "ho5", name: "Storage" },
    { id: "ho6", name: "Commercial and Business" },
    { id: "ho7", name: "Apartments and Housing for rent" },
  ],
  Gigs: [
    { id: "gi1", name: "Electronic" },
    { id: "gi2", name: "General Labor" },
    { id: "gi3", name: "Writing" },
  ],
  ForSale: [
    { id: "fs1", name: "Toys/Games/Video Games" },
    { id: "fs2", name: "Trailers/RVs/Mobile Homes" },
    { id: "fs3", name: "Tools and Machines" },
    { id: "fs4", name: "Event Tickets" },
    { id: "fs5", name: "Sporting Goods" },
    { id: "fs6", name: "Musical Instruments" },
    { id: "fs7", name: "Motorcycles & Motorcycle Parts" },
    { id: "fs8", name: "Building Materials" },
    { id: "fs9", name: "Jewelry" },
    { id: "fs10", name: "Household/Farm/Garden" },
    { id: "fs11", name: "Free" },
    { id: "fs12", name: "Antiques and Furniture" },
    { id: "fs13", name: "Electronics" },
    { id: "fs14", name: "Computer and Computer Parts" },
    { id: "fs15", name: "Clothes" },
    { id: "fs16", name: "Cell Phones" },
    { id: "fs17", name: "Cars and Trucks" },
    { id: "fs18", name: "Car and Truck Parts/Tires/Wheels" },
    { id: "fs19", name: "Business" },
    { id: "fs20", name: "Book" },
    { id: "fs21", name: "Boats and Boat Parts" },
    { id: "fs22", name: "Bike and Bike Parts" },
    { id: "fs23", name: "Health and Beauty" },
    { id: "fs24", name: "ATVs and UTVs" },
  ],
  Jobs: [
    { id: "jo1", name: "Writing" },
    { id: "jo2", name: "Computer" },
    { id: "jo3", name: "Media" },
    { id: "jo4", name: "Transportation" },
    { id: "jo5", name: "Business" },
    { id: "jo6", name: "Skilled Technicians" },
    { id: "jo7", name: "Security" },
    { id: "jo8", name: "Science" },
    { id: "jo9", name: "Beauty and Fitness" },
    { id: "jo10", name: "Retail" },
    { id: "jo11", name: "Real Estate" },
    { id: "jo12", name: "Finance" },
    { id: "jo13", name: "Education" },
    { id: "jo14", name: "Engineering" },
    { id: "jo15", name: "Customer Service" },
    { id: "jo16", name: "General Labor and Manufacturing" },
    { id: "jo17", name: "Nonprofit" },
    { id: "jo18", name: "Office" },
  ],
  LegalHelp: [
    { id: "lh1", name: "Maritime" },
    { id: "lh2", name: "Bankruptcy" },
    { id: "lh3", name: "Business Law" },
    { id: "lh4", name: "Civil Rights" },
    { id: "lh5", name: "Entertainment" },
    { id: "lh6", name: "Environment" },
    { id: "lh7", name: "Family" },
    { id: "lh8", name: "Health" },
    { id: "lh9", name: "Immigration" },
    { id: "lh10", name: "Intellectual" },
    { id: "lh11", name: "International" },
    { id: "lh12", name: "Labor" },
    { id: "lh13", name: "Military" },
    { id: "lh14", name: "Personal" },
    { id: "lh15", name: "Tax" },
  ],
}

export const adsListExpand = [
  {
    title: "Services",
    image: require("../../assets/Services.svg"),
    content: [
      { id: "se1", name: "Skilled Technician" },
      { id: "se2", name: "Real Estate" },
      { id: "se3", name: "Animal" },
      { id: "se4", name: "Aquatic" },
      { id: "se5", name: "Lessons and Educational Development" },
      { id: "se7", name: "General Labor and Moving" },
      { id: "se8", name: "Household/Farm/Garden" },
      { id: "se9", name: "Financial" },
      { id: "se10", name: "Ceremony and Event" },
      { id: "se11", name: "Electronic" },
      { id: "se12", name: "Beauty" },
      { id: "se13", name: "Automobile" },
    ],
  },
  {
    title: "Housing",
    image: require("../../assets/Housing.svg"),
    content: [
      { id: "ho1", name: "Vacation Rentals" },
      { id: "ho2", name: "Sublease" },
      { id: "ho3", name: "Rooms" },
      { id: "ho4", name: "Real Estate" },
      { id: "ho5", name: "Storage" },
      { id: "ho6", name: "Commercial and Business" },
      { id: "ho7", name: "Apartments and Housing for rent" },
    ],
  },
  {
    title: "Gigs",
    image: require("../../assets/Gigs.svg"),
    content: [
      { id: "gi1", name: "Electronic" },
      { id: "gi2", name: "General Labor" },
      { id: "gi3", name: "Writing" },
    ],
  },
  {
    title: "ForSale",
    image: require("../../assets/ForSale.svg"),
    content: [
      { id: "fs1", name: "Toys/Games/Video Games" },
      { id: "fs2", name: "Trailers/RVs/Mobile Homes" },
      { id: "fs3", name: "Tools and Machines" },
      { id: "fs4", name: "Event Tickets" },
      { id: "fs5", name: "Sporting Goods" },
      { id: "fs6", name: "Musical Instruments" },
      { id: "fs7", name: "Motorcycles & Motorcycle Parts" },
      { id: "fs8", name: "Building Materials" },
      { id: "fs9", name: "Jewelry" },
      { id: "fs10", name: "Household/Farm/Garden" },
      { id: "fs11", name: "Free" },
      { id: "fs12", name: "Antiques and Furniture" },
      { id: "fs13", name: "Electronics" },
      { id: "fs14", name: "Computer and Computer Parts" },
      { id: "fs15", name: "Clothes" },
      { id: "fs16", name: "Cell Phones" },
      { id: "fs17", name: "Cars and Trucks" },
      { id: "fs18", name: "Car and Truck Parts/Tires/Wheels" },
      { id: "fs19", name: "Business" },
      { id: "fs20", name: "Book" },
      { id: "fs21", name: "Boats and Boat Parts" },
      { id: "fs22", name: "Bike and Bike Parts" },
      { id: "fs23", name: "Health and Beauty" },
      { id: "fs24", name: "ATVs and UTVs" },
    ],
  },
  {
    title: "Jobs",
    image: require("../../assets/Jobs.svg"),
    content: [
      { id: "jo1", name: "Writing" },
      { id: "jo2", name: "Computer" },
      { id: "jo3", name: "Media" },
      { id: "jo4", name: "Transportation" },
      { id: "jo5", name: "Business" },
      { id: "jo6", name: "Skilled Technicians" },
      { id: "jo7", name: "Security" },
      { id: "jo8", name: "Science" },
      { id: "jo9", name: "Beauty and Fitness" },
      { id: "jo10", name: "Retail" },
      { id: "jo11", name: "Real Estate" },
      { id: "jo12", name: "Finance" },
      { id: "jo13", name: "Education" },
      { id: "jo14", name: "Engineering" },
      { id: "jo15", name: "Customer Service" },
      { id: "jo16", name: "General Labor and Manufacturing" },
      { id: "jo17", name: "Nonprofit" },
      { id: "jo18", name: "Office" },
    ],
  },
  {
    title: "LegalHelp",
    image: require("../../assets/LegalHelp.svg"),
    content: [
      { id: "lh1", name: "Maritime" },
      { id: "lh2", name: "Bankruptcy" },
      { id: "lh3", name: "Business Law" },
      { id: "lh4", name: "Civil Rights" },
      { id: "lh5", name: "Entertainment" },
      { id: "lh6", name: "Environment" },
      { id: "lh7", name: "Family" },
      { id: "lh8", name: "Health" },
      { id: "lh9", name: "Immigration" },
      { id: "lh10", name: "Intellectual" },
      { id: "lh11", name: "International" },
      { id: "lh12", name: "Labor" },
      { id: "lh13", name: "Military" },
      { id: "lh14", name: "Personal" },
      { id: "lh15", name: "Tax" },
    ],
  },
]
export const USSTATES = [
  {
    name: "Alabama",
    abbreviation: "AL",
  },
  {
    name: "Alaska",
    abbreviation: "AK",
  },
  {
    name: "American Samoa",
    abbreviation: "AS",
  },
  {
    name: "Arizona",
    abbreviation: "AZ",
  },
  {
    name: "Arkansas",
    abbreviation: "AR",
  },
  {
    name: "California",
    abbreviation: "CA",
  },
  {
    name: "Colorado",
    abbreviation: "CO",
  },
  {
    name: "Connecticut",
    abbreviation: "CT",
  },
  {
    name: "Delaware",
    abbreviation: "DE",
  },
  {
    name: "District Of Columbia",
    abbreviation: "DC",
  },
  {
    name: "Federated States Of Micronesia",
    abbreviation: "FM",
  },
  {
    name: "Florida",
    abbreviation: "FL",
  },
  {
    name: "Georgia",
    abbreviation: "GA",
  },
  {
    name: "Guam",
    abbreviation: "GU",
  },
  {
    name: "Hawaii",
    abbreviation: "HI",
  },
  {
    name: "Idaho",
    abbreviation: "ID",
  },
  {
    name: "Illinois",
    abbreviation: "IL",
  },
  {
    name: "Indiana",
    abbreviation: "IN",
  },
  {
    name: "Iowa",
    abbreviation: "IA",
  },
  {
    name: "Kansas",
    abbreviation: "KS",
  },
  {
    name: "Kentucky",
    abbreviation: "KY",
  },
  {
    name: "Louisiana",
    abbreviation: "LA",
  },
  {
    name: "Maine",
    abbreviation: "ME",
  },
  {
    name: "Marshall Islands",
    abbreviation: "MH",
  },
  {
    name: "Maryland",
    abbreviation: "MD",
  },
  {
    name: "Massachusetts",
    abbreviation: "MA",
  },
  {
    name: "Michigan",
    abbreviation: "MI",
  },
  {
    name: "Minnesota",
    abbreviation: "MN",
  },
  {
    name: "Mississippi",
    abbreviation: "MS",
  },
  {
    name: "Missouri",
    abbreviation: "MO",
  },
  {
    name: "Montana",
    abbreviation: "MT",
  },
  {
    name: "Nebraska",
    abbreviation: "NE",
  },
  {
    name: "Nevada",
    abbreviation: "NV",
  },
  {
    name: "New Hampshire",
    abbreviation: "NH",
  },
  {
    name: "New Jersey",
    abbreviation: "NJ",
  },
  {
    name: "New Mexico",
    abbreviation: "NM",
  },
  {
    name: "New York",
    abbreviation: "NY",
  },
  {
    name: "North Carolina",
    abbreviation: "NC",
  },
  {
    name: "North Dakota",
    abbreviation: "ND",
  },
  {
    name: "Northern Mariana Islands",
    abbreviation: "MP",
  },
  {
    name: "Ohio",
    abbreviation: "OH",
  },
  {
    name: "Oklahoma",
    abbreviation: "OK",
  },
  {
    name: "Oregon",
    abbreviation: "OR",
  },
  {
    name: "Palau",
    abbreviation: "PW",
  },
  {
    name: "Pennsylvania",
    abbreviation: "PA",
  },
  {
    name: "Puerto Rico",
    abbreviation: "PR",
  },
  {
    name: "Rhode Island",
    abbreviation: "RI",
  },
  {
    name: "South Carolina",
    abbreviation: "SC",
  },
  {
    name: "South Dakota",
    abbreviation: "SD",
  },
  {
    name: "Tennessee",
    abbreviation: "TN",
  },
  {
    name: "Texas",
    abbreviation: "TX",
  },
  {
    name: "Utah",
    abbreviation: "UT",
  },
  {
    name: "Vermont",
    abbreviation: "VT",
  },
  {
    name: "Virgin Islands",
    abbreviation: "VI",
  },
  {
    name: "Virginia",
    abbreviation: "VA",
  },
  {
    name: "Washington",
    abbreviation: "WA",
  },
  {
    name: "West Virginia",
    abbreviation: "WV",
  },
  {
    name: "Wisconsin",
    abbreviation: "WI",
  },
  {
    name: "Wyoming",
    abbreviation: "WY",
  },
]
export const UsStatesWithCities = [
  {
    state: "Alabama",
    cities: [
      "auburn",
      "birmingham",
      "dothan",
      "florence / muscle shoals",
      "gadsden-anniston",
      "huntsville / decatur",
      "mobile",
      "montgomery",
      "tuscaloosa",
    ],
  },
  {
    state: "Alaska",
    cities: ["anchorage / mat-su", "fairbanks", "kenai peninsula", "southeast alaska"],
  },
  {
    state: "Arizona",
    cities: [
      "flagstaff / sedona",
      "mohave county",
      "phoenix",
      "prescott",
      "show low",
      "sierra vista",
      "tucson",
      "yuma",
    ],
  },
  {
    state: "Arkansas",
    cities: ["fayetteville", "fort smith", "jonesboro", "little rock", "texarkana"],
  },
  {
    state: "California",
    cities: [
      "bakersfield",
      "chico",
      "fresno / madera",
      "gold country",
      "hanford - corcoran",
      "humboldt county",
      "imperial county",
      "inland empire",
      "los angeles",
      "mendocino county",
      "merced",
      "modesto",
      "monterey bay",
      "orange county",
      "palm springs",
      "redding",
      "sacramento",
      "san diego",
      "san francisco bay area",
      "san luis obispo",
      "santa barbara",
      "santa maria",
      "siskiyou county",
      "stockton",
      "susanville",
      "ventura county",
      "visalia - tulare",
      "yuba - sutter",
    ],
  },
  {
    state: "Colorado",
    cities: [
      "boulder",
      "colorado springs",
      "denver",
      "eastern CO",
      "fort collins / north CO",
      "high rockies",
      "pueblo",
      "western slope",
    ],
  },
  {
    state: "Connecticut",
    cities: ["eastern CT", "hartford", "new haven", "northwest CT"],
  },
  {
    state: "Delaware",
    cities: ["delaware"],
  },
  {
    state: "District of Columbia",
    cities: ["washington"],
  },
  {
    state: "Florida",
    cities: [
      "broward county",
      "daytona beach",
      "florida keys",
      "fort lauderdale",
      "ft myers / SW florida",
      "gainesville",
      "heartland florida",
      "jacksonville",
      "lakeland",
      "miami / dade",
      "north central FL",
      "ocala",
      "okaloosa / walton",
      "orlando",
      "panama city",
      "pensacola",
      "sarasota - bradenton",
      "south florida",
      "space coast",
      "st augustine",
      "tallahassee",
      "tampa bay area",
      "treasure coast",
      "palm beach county",
    ],
  },
  {
    state: "Georgia",
    cities: [
      "albany",
      "athens",
      "atlanta",
      "augusta",
      "brunswick",
      "columbus",
      "macon / warner robins",
      "northwest GA",
      "savannah / hinesville",
      "statesboro",
      "valdosta",
    ],
  },
  {
    state: "Hawaii",
    cities: ["hawaii"],
  },
  {
    state: "Idaho",
    cities: ["boise", "east idaho", "lewiston / clarkston", "twin falls"],
  },
  {
    state: "Illinois",
    cities: [
      "bloomington - normal",
      "champaign urbana",
      "chicago",
      "decatur",
      "la salle co",
      "mattoon - charleston",
      "peoria",
      "rockford",
      "southern illinois",
      "springfield",
      "western IL",
    ],
  },
  {
    state: "Indiana",
    cities: [
      "bloomington",
      "evansville",
      "fort wayne",
      "indianapolis",
      "kokomo",
      "lafayette / west lafayette",
      "muncie / anderson",
      "richmond",
      "south bend / michiana",
      "terre haute",
    ],
  },
  {
    state: "Iowa",
    cities: [
      "ames",
      "cedar rapids",
      "des moines",
      "dubuque",
      "fort dodge",
      "iowa city",
      "mason city",
      "quad cities",
      "sioux city",
      "southeast IA",
      "waterloo / cedar falls",
    ],
  },
  {
    state: "Kansas",
    cities: [
      "lawrence",
      "manhattan",
      "northwest KS",
      "salina",
      "southeast KS",
      "southwest KS",
      "topeka",
      "wichita",
    ],
  },
  {
    state: "Kentucky",
    cities: [
      "bowling green",
      "eastern kentucky",
      "lexington",
      "louisville",
      "owensboro",
      "western KY",
    ],
  },
  {
    state: "Louisiana",
    cities: [
      "baton rouge",
      "central louisiana",
      "houma",
      "lafayette",
      "lake charles",
      "monroe",
      "new orleans",
      "shreveport",
    ],
  },
  {
    state: "Maine",
    cities: ["maine"],
  },
  {
    state: "Maryland",
    cities: [
      "annapolis",
      "baltimore",
      "eastern shore",
      "frederick",
      "southern maryland",
      "western maryland",
    ],
  },
  {
    state: "Massachusetts",
    cities: [
      "boston",
      "cape cod / islands",
      "south coast",
      "western massachusetts",
      "worcester / central MA",
    ],
  },
  {
    state: "Michigan",
    cities: [
      "ann arbor",
      "battle creek",
      "central michigan",
      "detroit metro",
      "flint",
      "grand rapids",
      "holland",
      "jackson",
      "kalamazoo",
      "lansing",
      "monroe",
      "muskegon",
      "northern michigan",
      "port huron",
      "saginaw - midland - baycity",
      "southwest michigan",
      "the thumb",
      "upper peninsula",
    ],
  },
  {
    state: "Minnesota",
    cities: [
      "bemidji",
      "brainerd",
      "duluth / superior",
      "mankato",
      "minneapolis / st paul",
      "rochester",
      "southwest MN",
      "st cloud",
    ],
  },
  {
    state: "Mississippi",
    cities: [
      "gulfport / biloxi",
      "hattiesburg",
      "jackson",
      "meridian",
      "north mississippi",
      "southwest MS",
    ],
  },
  {
    state: "Missouri",
    cities: [
      "columbia / jeff city",
      "joplin",
      "kansas city",
      "kirksville",
      "lake of the ozarks",
      "southeast missouri",
      "springfield",
      "st joseph",
      "st louis",
    ],
  },
  {
    state: "Montana",
    cities: [
      "billings",
      "bozeman",
      "butte",
      "great falls",
      "helena",
      "kalispell",
      "missoula",
      "eastern montana",
    ],
  },
  {
    state: "Nebraska",
    cities: [
      "grand island",
      "lincoln",
      "north platte",
      "omaha / council bluffs",
      "scottsbluff / panhandle",
    ],
  },
  {
    state: "Nevada",
    cities: ["elko", "las vegas", "reno / tahoe"],
  },
  {
    state: "New Hampshire",
    cities: ["new hampshire"],
  },
  {
    state: "New Jersey",
    cities: ["central NJ", "jersey shore", "north jersey", "south jersey"],
  },
  {
    state: "New Mexico",
    cities: [
      "albuquerque",
      "clovis / portales",
      "farmington",
      "las cruces",
      "roswell / carlsbad",
      "santa fe / taos",
    ],
  },
  {
    state: "New York",
    cities: [
      "albany",
      "binghamton",
      "buffalo",
      "catskills",
      "chautauqua",
      "elmira - corning",
      "finger lakes",
      "glens falls",
      "hudson valley",
      "ithaca",
      "long island",
      "new york city",
      "oneonta",
      "plattsburgh - adirondacks",
      "potsdam - canton - massena",
      "rochester",
      "syracuse",
      "twin tiers NY / PA",
      "utica - rome - oneida",
      "watertown",
    ],
  },
  {
    state: "North Carolina",
    cities: [
      "asheville",
      "boone",
      "charlotte",
      "eastern NC",
      "fayetteville",
      "greensboro",
      "hickory / lenoir",
      "jacksonville",
      "outer banks",
      "raleigh / durham / CH",
      "wilmington",
      "winston - salem",
    ],
  },
  {
    state: "North Dakota",
    cities: ["bismarck", "fargo / moorhead", "grand forks", "north dakota"],
  },
  {
    state: "Ohio",
    cities: [
      "akron / canton",
      "ashtabula",
      "athens",
      "chillicothe",
      "cincinnati",
      "cleveland",
      "columbus",
      "dayton / springfield",
      "lima / findlay",
      "mansfield",
      "sandusky",
      "toledo",
      "tuscarawas co",
      "youngstown",
      "zanesville / cambridge",
    ],
  },
  {
    state: "Oklahoma",
    cities: ["lawton", "northwest OK", "oklahoma city", "stillwater", "tulsa"],
  },
  {
    state: "Oregon",
    cities: [
      "bend",
      "corvallis / albany",
      "east oregon",
      "eugene",
      "klamath falls",
      "medford - ashland",
      "oregon coast",
      "portland",
      "roseburg",
      "salem",
    ],
  },
  {
    state: "Pennsylvania",
    cities: [
      "altoona - johnstown",
      "cumberland valley",
      "erie",
      "harrisburg",
      "lancaster",
      "lehigh valley",
      "meadville",
      "philadelphia",
      "pittsburgh",
      "poconos",
      "reading",
      "scranton / wilkes - barre",
      "state college",
      "williamsport",
      "york",
    ],
  },
  {
    state: "Rhode Island",
    cities: ["rhode island"],
  },
  {
    state: "South Carolina",
    cities: [
      "charleston",
      "columbia",
      "florence",
      "greenville / upstate",
      "hilton head",
      "myrtle beach",
    ],
  },
  {
    state: "South Dakota",
    cities: [
      "northeast SD",
      "pierre / central SD",
      "rapid city / west SD",
      "sioux falls / SE SD",
      "south dakota",
    ],
  },
  {
    state: "Tennessee",
    cities: [
      "chattanooga",
      "clarksville",
      "cookeville",
      "jackson",
      "knoxville",
      "memphis",
      "nashville",
      "tri - cities",
    ],
  },
  {
    state: "Texas",
    cities: [
      "abilene",
      "amarillo",
      "austin",
      "beaumont / port arthur",
      "brownsville",
      "college station",
      "corpus christi",
      "dallas / fort worth",
      "deep east texas",
      "del rio / eagle pass",
      "el paso",
      "galveston",
      "houston",
      "killeen / temple / ft hood",
      "laredo",
      "lubbock",
      "mcallen / edinburg",
      "odessa / midland",
      "san angelo",
      "san antonio",
      "san marcos",
      "southwest TX",
      "texoma",
      "tyler / east TX",
      "victoria",
      "waco",
      "wichita falls",
    ],
  },
  {
    state: "Utah",
    cities: ["logan", "ogden - clearfield", "provo / orem", "salt lake city", "st george"],
  },
  {
    state: "Vermont",
    cities: ["vermont"],
  },
  {
    state: "Virginia",
    cities: [
      "charlottesville",
      "danville",
      "fredericksburg",
      "hampton roads",
      "harrisonburg",
      "lynchburg",
      "new river valley",
      "richmond",
      "roanoke",
      "southwest VA",
      "winchester",
    ],
  },
  {
    state: "Washington",
    cities: [
      "bellingham",
      "kennewick - pasco - richland",
      "moses lake",
      "olympic peninsula",
      "pullman / moscow",
      "seattle - tacoma",
      "skagit / island / SJI",
      "spokane / coeur d ]alene",
      "wenatchee",
      "yakima",
    ],
  },
  {
    state: "West Virginia",
    cities: [
      "charleston",
      "eastern panhandle",
      "huntington - ashland",
      "morgantown",
      "northern panhandle",
      "parkersburg - marietta",
      "southern WV",
      "west virginia(old)",
    ],
  },
  {
    state: "Wisconsin",
    cities: [
      "appleton - oshkosh - FDL",
      "eau claire",
      "green bay",
      "janesville",
      "kenosha - racine",
      "la crosse",
      "madison",
      "milwaukee",
      "northern WI",
      "sheboygan",
      "wausau",
    ],
  },
  {
    state: "Wyoming",
    cities: ["wyoming"],
  },
]
export const UsStatesWithCitiesOld = [
  {
    state: "New York",
    cities: [
      "New York",
      "Buffalo",
      "Rochester",
      "Yonkers",
      "Syracuse",
      "Albany",
      "New Rochelle",
      "Mount Vernon",
      "Schenectady",
      "Utica",
      "White Plains",
      "Hempstead",
      "Troy",
      "Niagara Falls",
      "Binghamton",
      "Freeport",
      "Valley Stream",
    ],
  },
  {
    state: "California",
    cities: [
      "Los Angeles",
      "San Diego",
      "San Jose",
      "San Francisco",
      "Fresno",
      "Sacramento",
      "Long Beach",
      "Oakland",
      "Bakersfield",
      "Anaheim",
      "Santa Ana",
      "Riverside",
      "Stockton",
      "Chula Vista",
      "Irvine",
      "Fremont",
      "San Bernardino",
      "Modesto",
      "Fontana",
      "Oxnard",
      "Moreno Valley",
      "Huntington Beach",
      "Glendale",
      "Santa Clarita",
      "Garden Grove",
      "Oceanside",
      "Rancho Cucamonga",
      "Santa Rosa",
      "Ontario",
      "Lancaster",
      "Elk Grove",
      "Corona",
      "Palmdale",
      "Salinas",
      "Pomona",
      "Hayward",
      "Escondido",
      "Torrance",
      "Sunnyvale",
      "Orange",
      "Fullerton",
      "Pasadena",
      "Thousand Oaks",
      "Visalia",
      "Simi Valley",
      "Concord",
      "Roseville",
      "Victorville",
      "Santa Clara",
      "Vallejo",
      "Berkeley",
      "El Monte",
      "Downey",
      "Costa Mesa",
      "Inglewood",
      "Carlsbad",
      "San Buenaventura (Ventura)",
      "Fairfield",
      "West Covina",
      "Murrieta",
      "Richmond",
      "Norwalk",
      "Antioch",
      "Temecula",
      "Burbank",
      "Daly City",
      "Rialto",
      "Santa Maria",
      "El Cajon",
      "San Mateo",
      "Clovis",
      "Compton",
      "Jurupa Valley",
      "Vista",
      "South Gate",
      "Mission Viejo",
      "Vacaville",
      "Carson",
      "Hesperia",
      "Santa Monica",
      "Westminster",
      "Redding",
      "Santa Barbara",
      "Chico",
      "Newport Beach",
      "San Leandro",
      "San Marcos",
      "Whittier",
      "Hawthorne",
      "Citrus Heights",
      "Tracy",
      "Alhambra",
      "Livermore",
      "Buena Park",
      "Menifee",
      "Hemet",
      "Lakewood",
      "Merced",
      "Chino",
      "Indio",
      "Redwood City",
      "Lake Forest",
      "Napa",
      "Tustin",
      "Bellflower",
      "Mountain View",
      "Chino Hills",
      "Baldwin Park",
      "Alameda",
      "Upland",
      "San Ramon",
      "Folsom",
      "Pleasanton",
      "Union City",
      "Perris",
      "Manteca",
      "Lynwood",
      "Apple Valley",
      "Redlands",
      "Turlock",
      "Milpitas",
      "Redondo Beach",
      "Rancho Cordova",
      "Yorba Linda",
      "Palo Alto",
      "Davis",
      "Camarillo",
      "Walnut Creek",
      "Pittsburg",
      "South San Francisco",
      "Yuba City",
      "San Clemente",
      "Laguna Niguel",
      "Pico Rivera",
      "Montebello",
      "Lodi",
      "Madera",
      "Santa Cruz",
      "La Habra",
      "Encinitas",
      "Monterey Park",
      "Tulare",
      "Cupertino",
      "Gardena",
      "National City",
      "Rocklin",
      "Petaluma",
      "Huntington Park",
      "San Rafael",
      "La Mesa",
      "Arcadia",
      "Fountain Valley",
      "Diamond Bar",
      "Woodland",
      "Santee",
      "Lake Elsinore",
      "Porterville",
      "Paramount",
      "Eastvale",
      "Rosemead",
      "Hanford",
      "Highland",
      "Brentwood",
      "Novato",
      "Colton",
      "Cathedral City",
      "Delano",
      "Yucaipa",
      "Watsonville",
      "Placentia",
      "Glendora",
      "Gilroy",
      "Palm Desert",
      "Cerritos",
      "West Sacramento",
      "Aliso Viejo",
      "Poway",
      "La Mirada",
      "Rancho Santa Margarita",
      "Cypress",
      "Dublin",
      "Covina",
      "Azusa",
      "Palm Springs",
      "San Luis Obispo",
      "Ceres",
      "San Jacinto",
      "Lincoln",
      "Newark",
      "Lompoc",
      "El Centro",
      "Danville",
      "Bell Gardens",
      "Coachella",
      "Rancho Palos Verdes",
      "San Bruno",
      "Rohnert Park",
      "Brea",
      "La Puente",
      "Campbell",
      "San Gabriel",
      "Beaumont",
      "Morgan Hill",
      "Culver City",
      "Calexico",
      "Stanton",
      "La Quinta",
      "Pacifica",
      "Montclair",
      "Oakley",
      "Monrovia",
      "Los Banos",
      "Martinez",
    ],
  },
  {
    state: "Illinois",
    cities: [
      "Chicago",
      "Aurora",
      "Rockford",
      "Joliet",
      "Naperville",
      "Springfield",
      "Peoria",
      "Elgin",
      "Waukegan",
      "Cicero",
      "Champaign",
      "Bloomington",
      "Arlington Heights",
      "Evanston",
      "Decatur",
      "Schaumburg",
      "Bolingbrook",
      "Palatine",
      "Skokie",
      "Des Plaines",
      "Orland Park",
      "Tinley Park",
      "Oak Lawn",
      "Berwyn",
      "Mount Prospect",
      "Normal",
      "Wheaton",
      "Hoffman Estates",
      "Oak Park",
      "Downers Grove",
      "Elmhurst",
      "Glenview",
      "DeKalb",
      "Lombard",
      "Belleville",
      "Moline",
      "Buffalo Grove",
      "Bartlett",
      "Urbana",
      "Quincy",
      "Crystal Lake",
      "Plainfield",
      "Streamwood",
      "Carol Stream",
      "Romeoville",
      "Rock Island",
      "Hanover Park",
      "Carpentersville",
      "Wheeling",
      "Park Ridge",
      "Addison",
      "Calumet City",
    ],
  },
  {
    state: "Texas",
    cities: [
      "Houston",
      "San Antonio",
      "Dallas",
      "Austin",
      "Fort Worth",
      "El Paso",
      "Arlington",
      "Corpus Christi",
      "Plano",
      "Laredo",
      "Lubbock",
      "Garland",
      "Irving",
      "Amarillo",
      "Grand Prairie",
      "Brownsville",
      "Pasadena",
      "McKinney",
      "Mesquite",
      "McAllen",
      "Killeen",
      "Frisco",
      "Waco",
      "Carrollton",
      "Denton",
      "Midland",
      "Abilene",
      "Beaumont",
      "Round Rock",
      "Odessa",
      "Wichita Falls",
      "Richardson",
      "Lewisville",
      "Tyler",
      "College Station",
      "Pearland",
      "San Angelo",
      "Allen",
      "League City",
      "Sugar Land",
      "Longview",
      "Edinburg",
      "Mission",
      "Bryan",
      "Baytown",
      "Pharr",
      "Temple",
      "Missouri City",
      "Flower Mound",
      "Harlingen",
      "North Richland Hills",
      "Victoria",
      "Conroe",
      "New Braunfels",
      "Mansfield",
      "Cedar Park",
      "Rowlett",
      "Port Arthur",
      "Euless",
      "Georgetown",
      "Pflugerville",
      "DeSoto",
      "San Marcos",
      "Grapevine",
      "Bedford",
      "Galveston",
      "Cedar Hill",
      "Texas City",
      "Wylie",
      "Haltom City",
      "Keller",
      "Coppell",
      "Rockwall",
      "Huntsville",
      "Duncanville",
      "Sherman",
      "The Colony",
      "Burleson",
      "Hurst",
      "Lancaster",
      "Texarkana",
      "Friendswood",
      "Weslaco",
    ],
  },
  {
    state: "Pennsylvania",
    cities: [
      "Philadelphia",
      "Pittsburgh",
      "Allentown",
      "Erie",
      "Reading",
      "Scranton",
      "Bethlehem",
      "Lancaster",
      "Harrisburg",
      "Altoona",
      "York",
      "State College",
      "Wilkes-Barre",
    ],
  },
  {
    state: "Arizona",
    cities: [
      "Phoenix",
      "Tucson",
      "Mesa",
      "Chandler",
      "Glendale",
      "Scottsdale",
      "Gilbert",
      "Tempe",
      "Peoria",
      "Surprise",
      "Yuma",
      "Avondale",
      "Goodyear",
      "Flagstaff",
      "Buckeye",
      "Lake Havasu City",
      "Casa Grande",
      "Sierra Vista",
      "Maricopa",
      "Oro Valley",
      "Prescott",
      "Bullhead City",
      "Prescott Valley",
      "Marana",
      "Apache Junction",
    ],
  },
  {
    state: "Florida",
    cities: [
      "Jacksonville",
      "Miami",
      "Tampa",
      "Orlando",
      "St. Petersburg",
      "Hialeah",
      "Tallahassee",
      "Fort Lauderdale",
      "Port St. Lucie",
      "Cape Coral",
      "Pembroke Pines",
      "Hollywood",
      "Miramar",
      "Gainesville",
      "Coral Springs",
      "Miami Gardens",
      "Clearwater",
      "Palm Bay",
      "Pompano Beach",
      "West Palm Beach",
      "Lakeland",
      "Davie",
      "Miami Beach",
      "Sunrise",
      "Plantation",
      "Boca Raton",
      "Deltona",
      "Largo",
      "Deerfield Beach",
      "Palm Coast",
      "Melbourne",
      "Boynton Beach",
      "Lauderhill",
      "Weston",
      "Fort Myers",
      "Kissimmee",
      "Homestead",
      "Tamarac",
      "Delray Beach",
      "Daytona Beach",
      "North Miami",
      "Wellington",
      "North Port",
      "Jupiter",
      "Ocala",
      "Port Orange",
      "Margate",
      "Coconut Creek",
      "Sanford",
      "Sarasota",
      "Pensacola",
      "Bradenton",
      "Palm Beach Gardens",
      "Pinellas Park",
      "Coral Gables",
      "Doral",
      "Bonita Springs",
      "Apopka",
      "Titusville",
      "North Miami Beach",
      "Oakland Park",
      "Fort Pierce",
      "North Lauderdale",
      "Cutler Bay",
      "Altamonte Springs",
      "St. Cloud",
      "Greenacres",
      "Ormond Beach",
      "Ocoee",
      "Hallandale Beach",
      "Winter Garden",
      "Aventura",
    ],
  },
  {
    state: "Indiana",
    cities: [
      "Indianapolis",
      "Fort Wayne",
      "Evansville",
      "South Bend",
      "Carmel",
      "Bloomington",
      "Fishers",
      "Hammond",
      "Gary",
      "Muncie",
      "Lafayette",
      "Terre Haute",
      "Kokomo",
      "Anderson",
      "Noblesville",
      "Greenwood",
      "Elkhart",
      "Mishawaka",
      "Lawrence",
      "Jeffersonville",
      "Columbus",
      "Portage",
    ],
  },
  {
    state: "Ohio",
    cities: [
      "Columbus",
      "Cleveland",
      "Cincinnati",
      "Toledo",
      "Akron",
      "Dayton",
      "Parma",
      "Canton",
      "Youngstown",
      "Lorain",
      "Hamilton",
      "Springfield",
      "Kettering",
      "Elyria",
      "Lakewood",
      "Cuyahoga Falls",
      "Middletown",
      "Euclid",
      "Newark",
      "Mansfield",
      "Mentor",
      "Beavercreek",
      "Cleveland Heights",
      "Strongsville",
      "Dublin",
      "Fairfield",
      "Findlay",
      "Warren",
      "Lancaster",
      "Lima",
      "Huber Heights",
      "Westerville",
      "Marion",
      "Grove City",
    ],
  },
  {
    state: "North Carolina",
    cities: [
      "Charlotte",
      "Raleigh",
      "Greensboro",
      "Durham",
      "Winston-Salem",
      "Fayetteville",
      "Cary",
      "Wilmington",
      "High Point",
      "Greenville",
      "Asheville",
      "Concord",
      "Gastonia",
      "Jacksonville",
      "Chapel Hill",
      "Rocky Mount",
      "Burlington",
      "Wilson",
      "Huntersville",
      "Kannapolis",
      "Apex",
      "Hickory",
      "Goldsboro",
    ],
  },
  {
    state: "Michigan",
    cities: [
      "Detroit",
      "Grand Rapids",
      "Warren",
      "Sterling Heights",
      "Ann Arbor",
      "Lansing",
      "Flint",
      "Dearborn",
      "Livonia",
      "Westland",
      "Troy",
      "Farmington Hills",
      "Kalamazoo",
      "Wyoming",
      "Southfield",
      "Rochester Hills",
      "Taylor",
      "Pontiac",
      "St. Clair Shores",
      "Royal Oak",
      "Novi",
      "Dearborn Heights",
      "Battle Creek",
      "Saginaw",
      "Kentwood",
      "East Lansing",
      "Roseville",
      "Portage",
      "Midland",
      "Lincoln Park",
      "Muskegon",
    ],
  },
  {
    state: "Tennessee",
    cities: [
      "Memphis",
      "Nashville-Davidson",
      "Knoxville",
      "Chattanooga",
      "Clarksville",
      "Murfreesboro",
      "Jackson",
      "Franklin",
      "Johnson City",
      "Bartlett",
      "Hendersonville",
      "Kingsport",
      "Collierville",
      "Cleveland",
      "Smyrna",
      "Germantown",
      "Brentwood",
    ],
  },
  {
    state: "Massachusetts",
    cities: [
      "Boston",
      "Worcester",
      "Springfield",
      "Lowell",
      "Cambridge",
      "New Bedford",
      "Brockton",
      "Quincy",
      "Lynn",
      "Fall River",
      "Newton",
      "Lawrence",
      "Somerville",
      "Waltham",
      "Haverhill",
      "Malden",
      "Medford",
      "Taunton",
      "Chicopee",
      "Weymouth Town",
      "Revere",
      "Peabody",
      "Methuen",
      "Barnstable Town",
      "Pittsfield",
      "Attleboro",
      "Everett",
      "Salem",
      "Westfield",
      "Leominster",
      "Fitchburg",
      "Beverly",
      "Holyoke",
      "Marlborough",
      "Woburn",
      "Chelsea",
    ],
  },
  {
    state: "Washington",
    cities: [
      "Seattle",
      "Spokane",
      "Tacoma",
      "Vancouver",
      "Bellevue",
      "Kent",
      "Everett",
      "Renton",
      "Yakima",
      "Federal Way",
      "Spokane Valley",
      "Bellingham",
      "Kennewick",
      "Auburn",
      "Pasco",
      "Marysville",
      "Lakewood",
      "Redmond",
      "Shoreline",
      "Richland",
      "Kirkland",
      "Burien",
      "Sammamish",
      "Olympia",
      "Lacey",
      "Edmonds",
      "Bremerton",
      "Puyallup",
    ],
  },
  {
    state: "Colorado",
    cities: [
      "Denver",
      "Colorado Springs",
      "Aurora",
      "Fort Collins",
      "Lakewood",
      "Thornton",
      "Arvada",
      "Westminster",
      "Pueblo",
      "Centennial",
      "Boulder",
      "Greeley",
      "Longmont",
      "Loveland",
      "Grand Junction",
      "Broomfield",
      "Castle Rock",
      "Commerce City",
      "Parker",
      "Littleton",
      "Northglenn",
    ],
  },
  { state: "District of Columbia", cities: ["Washington"] },
  {
    state: "Maryland",
    cities: [
      "Baltimore",
      "Frederick",
      "Rockville",
      "Gaithersburg",
      "Bowie",
      "Hagerstown",
      "Annapolis",
    ],
  },
  {
    state: "Kentucky",
    cities: [
      "Louisville/Jefferson County",
      "Lexington-Fayette",
      "Bowling Green",
      "Owensboro",
      "Covington",
    ],
  },
  {
    state: "Oregon",
    cities: [
      "Portland",
      "Eugene",
      "Salem",
      "Gresham",
      "Hillsboro",
      "Beaverton",
      "Bend",
      "Medford",
      "Springfield",
      "Corvallis",
      "Albany",
      "Tigard",
      "Lake Oswego",
      "Keizer",
    ],
  },
  {
    state: "Oklahoma",
    cities: [
      "Oklahoma City",
      "Tulsa",
      "Norman",
      "Broken Arrow",
      "Lawton",
      "Edmond",
      "Moore",
      "Midwest City",
      "Enid",
      "Stillwater",
      "Muskogee",
    ],
  },
  {
    state: "Wisconsin",
    cities: [
      "Milwaukee",
      "Madison",
      "Green Bay",
      "Kenosha",
      "Racine",
      "Appleton",
      "Waukesha",
      "Eau Claire",
      "Oshkosh",
      "Janesville",
      "West Allis",
      "La Crosse",
      "Sheboygan",
      "Wauwatosa",
      "Fond du Lac",
      "New Berlin",
      "Wausau",
      "Brookfield",
      "Greenfield",
      "Beloit",
    ],
  },
  {
    state: "Nevada",
    cities: ["Las Vegas", "Henderson", "Reno", "North Las Vegas", "Sparks", "Carson City"],
  },
  {
    state: "New Mexico",
    cities: [
      "Albuquerque",
      "Las Cruces",
      "Rio Rancho",
      "Santa Fe",
      "Roswell",
      "Farmington",
      "Clovis",
    ],
  },
  {
    state: "Missouri",
    cities: [
      "Kansas City",
      "St. Louis",
      "Springfield",
      "Independence",
      "Columbia",
      "Lee's Summit",
      "O'Fallon",
      "St. Joseph",
      "St. Charles",
      "St. Peters",
      "Blue Springs",
      "Florissant",
      "Joplin",
      "Chesterfield",
      "Jefferson City",
      "Cape Girardeau",
    ],
  },
  {
    state: "Virginia",
    cities: [
      "Virginia Beach",
      "Norfolk",
      "Chesapeake",
      "Richmond",
      "Newport News",
      "Alexandria",
      "Hampton",
      "Roanoke",
      "Portsmouth",
      "Suffolk",
      "Lynchburg",
      "Harrisonburg",
      "Leesburg",
      "Charlottesville",
      "Danville",
      "Blacksburg",
      "Manassas",
    ],
  },
  {
    state: "Georgia",
    cities: [
      "Atlanta",
      "Columbus",
      "Augusta-Richmond County",
      "Savannah",
      "Athens-Clarke County",
      "Sandy Springs",
      "Roswell",
      "Macon",
      "Johns Creek",
      "Albany",
      "Warner Robins",
      "Alpharetta",
      "Marietta",
      "Valdosta",
      "Smyrna",
      "Dunwoody",
    ],
  },
  {
    state: "Nebraska",
    cities: ["Omaha", "Lincoln", "Bellevue", "Grand Island"],
  },
  {
    state: "Minnesota",
    cities: [
      "Minneapolis",
      "St. Paul",
      "Rochester",
      "Duluth",
      "Bloomington",
      "Brooklyn Park",
      "Plymouth",
      "St. Cloud",
      "Eagan",
      "Woodbury",
      "Maple Grove",
      "Eden Prairie",
      "Coon Rapids",
      "Burnsville",
      "Blaine",
      "Lakeville",
      "Minnetonka",
      "Apple Valley",
      "Edina",
      "St. Louis Park",
      "Mankato",
      "Maplewood",
      "Moorhead",
      "Shakopee",
    ],
  },
  {
    state: "Kansas",
    cities: [
      "Wichita",
      "Overland Park",
      "Kansas City",
      "Olathe",
      "Topeka",
      "Lawrence",
      "Shawnee",
      "Manhattan",
      "Lenexa",
      "Salina",
      "Hutchinson",
    ],
  },
  {
    state: "Louisiana",
    cities: [
      "New Orleans",
      "Baton Rouge",
      "Shreveport",
      "Lafayette",
      "Lake Charles",
      "Kenner",
      "Bossier City",
      "Monroe",
      "Alexandria",
    ],
  },
  { state: "Hawaii", cities: ["Honolulu"] },
  { state: "Alaska", cities: ["Anchorage"] },
  {
    state: "New Jersey",
    cities: [
      "Newark",
      "Jersey City",
      "Paterson",
      "Elizabeth",
      "Clifton",
      "Trenton",
      "Camden",
      "Passaic",
      "Union City",
      "Bayonne",
      "East Orange",
      "Vineland",
      "New Brunswick",
      "Hoboken",
      "Perth Amboy",
      "West New York",
      "Plainfield",
      "Hackensack",
      "Sayreville",
      "Kearny",
      "Linden",
      "Atlantic City",
    ],
  },
  {
    state: "Idaho",
    cities: [
      "Boise City",
      "Nampa",
      "Meridian",
      "Idaho Falls",
      "Pocatello",
      "Caldwell",
      "Coeur d'Alene",
      "Twin Falls",
    ],
  },
  {
    state: "Alabama",
    cities: [
      "Birmingham",
      "Montgomery",
      "Mobile",
      "Huntsville",
      "Tuscaloosa",
      "Hoover",
      "Dothan",
      "Auburn",
      "Decatur",
      "Madison",
      "Florence",
      "Gadsden",
    ],
  },
  {
    state: "Iowa",
    cities: [
      "Des Moines",
      "Cedar Rapids",
      "Davenport",
      "Sioux City",
      "Iowa City",
      "Waterloo",
      "Council Bluffs",
      "Ames",
      "West Des Moines",
      "Dubuque",
      "Ankeny",
      "Urbandale",
      "Cedar Falls",
    ],
  },
  {
    state: "Arkansas",
    cities: [
      "Little Rock",
      "Fort Smith",
      "Fayetteville",
      "Springdale",
      "Jonesboro",
      "North Little Rock",
      "Conway",
      "Rogers",
      "Pine Bluff",
      "Bentonville",
    ],
  },
  {
    state: "Utah",
    cities: [
      "Salt Lake City",
      "West Valley City",
      "Provo",
      "West Jordan",
      "Orem",
      "Sandy",
      "Ogden",
      "St. George",
      "Layton",
      "Taylorsville",
      "South Jordan",
      "Lehi",
      "Logan",
      "Murray",
      "Draper",
      "Bountiful",
      "Riverton",
      "Roy",
    ],
  },
  {
    state: "Rhode Island",
    cities: ["Providence", "Warwick", "Cranston", "Pawtucket", "East Providence", "Woonsocket"],
  },
  {
    state: "Mississippi",
    cities: ["Jackson", "Gulfport", "Southaven", "Hattiesburg", "Biloxi", "Meridian"],
  },
  { state: "South Dakota", cities: ["Sioux Falls", "Rapid City"] },
  {
    state: "Connecticut",
    cities: [
      "Bridgeport",
      "New Haven",
      "Stamford",
      "Hartford",
      "Waterbury",
      "Norwalk",
      "Danbury",
      "New Britain",
      "Meriden",
      "Bristol",
      "West Haven",
      "Milford",
      "Middletown",
      "Norwich",
      "Shelton",
    ],
  },
  {
    state: "South Carolina",
    cities: [
      "Columbia",
      "Charleston",
      "North Charleston",
      "Mount Pleasant",
      "Rock Hill",
      "Greenville",
      "Summerville",
      "Sumter",
      "Goose Creek",
      "Hilton Head Island",
      "Florence",
      "Spartanburg",
    ],
  },
  { state: "New Hampshire", cities: ["Manchester", "Nashua", "Concord"] },
  {
    state: "North Dakota",
    cities: ["Fargo", "Bismarck", "Grand Forks", "Minot"],
  },
  {
    state: "Montana",
    cities: ["Billings", "Missoula", "Great Falls", "Bozeman"],
  },
  { state: "Delaware", cities: ["Wilmington", "Dover"] },
  { state: "Maine", cities: ["Portland"] },
  { state: "Wyoming", cities: ["Cheyenne", "Casper"] },
  { state: "West Virginia", cities: ["Charleston", "Huntington"] },
  { state: "Vermont", cities: ["Burlington"] },
]
